name: Frontend (client) and Backend (server) CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to the main branch

jobs:
  # Frontend (Client) Build and Test
  frontend:
    name: Client (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 for the frontend

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Test frontend
        run: |
          cd client
          npm test

  # Backend (Server) Build and Test
  backend:
    name: Server (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20 for the backend

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Test backend
        run: |
          cd server
          npm test

